version: '1'
services:
  db:
    container_name: db_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  backend:
    container_name: backend_node
    image: node-rm
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATASOURCE_URL=db
      - DATASOURCE_USERNAME=root
      - DATASOURCE_PASSWORD=root
    ports:
      - "3000:3000"

